# This Justfile contains rules/targets/scripts/commands that are used when
# developing. Unlike a Makefile, running `just <cmd>` will always invoke
# that command. For more information, see https://github.com/casey/just
#
#
# this setting will allow passing arguments through to tasks, see the docs here
# https://just.systems/man/en/chapter_24.html#positional-arguments
set positional-arguments
# print all available commands by default
default:
  just --list

# destroys and recreates the appdb postgres container
reset-db:
  docker compose down -v
  docker compose up -d appdb

# applies migrations and dumps schema.sql
migrate:
  pgmigrate migrate
  pgmigrate dump

# runs the app server
run:
  go run .

test:
  go test ./... -count=1 -race
