name: nix
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: nix run .#pgmigrate -- --help
  nix-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - run: nix flake check
    - run: |
        nix develop --command nixpkgs-fmt --check *.nix
        if ! git diff-index --quiet HEAD --; then
          echo "nixpkgs-fmt had changes"
          exit 1
        fi
