name: nix
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: build and run with nix
      run: nix run .#pgmigrate -- --help
  nix-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: flake check
      run: nix flake check
    - name: lint & format
      run: |
        nix develop --command nixpkgs-fmt --check *.nix
        if ! git diff-index --quiet HEAD --; then
          echo "nixpkgs-fmt had changes"
          exit 1
        fi
